### ISSUE TITLE
`api.cors.lol` is offline?

### ISSUE THREAD

**Issue by webash** [BradPerbs/cors.lol#3]
![image](https://github.com/user-attachments/assets/5aa636b4-d519-4cf3-942b-8d676198948e)

Hello! Seems the site `api.cors.lol` is offline. Is that expected?

**Comment by webash** [comment]
Hello @BradPerbs ! Just in case you hadn't seen this organically yet

**Comment by BradPerbs** [comment]
Issues has been fixed.
